#!/usr/bin/env bash

set -e

if snapctl is-connected qt-ozw-lib; then
    LIB_QT="$(dirname $(find ${SNAP}/usr/qt-ozw-lib* -name libqt-openzwave.so -print -quit))"
    LIB_OZW="$(dirname $(find ${SNAP}/usr/qt-ozw-lib* -name libopenzwave.so -print -quit))"
    if [ -z "${LD_LIBRARY_PATH}" ]; then
        export LD_LIBRARY_PATH="${LIB_QT}:${$LIB_OZW}"
    else
        export LD_LIBRARY_PATH="${LD_LIBRARY_PATH}:${LIB_QT}:${LIB_OZW}"
    fi
    export QT_PLUGIN_PATH="$(dirname $(dirname $(find "${SNAP}/usr/lib" -name libqxcb.so -print -quit)))"
    export LIBGL_DRIVERS_PATH=$(find "${SNAP}" -type d -name dri -print -quit)

    mkdir -p --mode=0700 "${XDG_RUNTIME_DIR}"
    unset SESSION_MANAGER
    exec "$@"
else
    echo "Please connect 'qt-ozw-lib'"
    echo "$ snap connect ${SNAP_NAME}:qt-ozw-lib ozwdaemon:qt-ozw-lib"
    exit 1
fi
